FinalCal/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/urls.py
from django.contrib import admin
from django.urls import path
from app import views

# Template urls
app_name = 'app'

urlpatterns = [
   path('register/', views.register, name='register'),
   path('', views.base.as_view(), name='base'),
   path('login/', views.user_login, name='login'),
   path('about/', views.about.as_view(), name='about'),
   path('logout/', views.user_logout, name='logout'),
   path('event/', views.create_event, name='event'),
   path('home/', views.CalanderView, name='calendar'),
   path('event_detail/<int:event_id>/', views.event_details, name='event_detail'),
   path('calendar2', views.calendar2, name='calendar2')
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Event(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) # ForeignKey is used to coincide Event with User class 
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    # Used to create a hyperlink on calendar to view event detail
    def get_html_url(self):
        url = reverse('app:event_detail', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

app/forms.py
from django import forms
from .models import Event
from django.contrib.auth.models import User

# Model form of model 'User' inbuilt in Django
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(required=True, label='Email',
                    widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    username = forms.CharField(max_length=20, label='Username',
                    widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    
    # Django Meta class used to transfer information about the model to the Django forms
    class Meta:
        model = User
        fields = ('username','email','password') # The generated Form class will have a form field for every model field specified, in the order specified in the fields attribute.

# Model form of model 'Event' in models.py
class EventForm(forms.ModelForm):
    # Django Meta class used to transfer information about the model to the Django forms
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': forms.DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': forms.DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    exclude = ['user'] # The exclude attribute tells Django what fields from the model not to include in the form.

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats to parse HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

app/views.py
from django.shortcuts import render
from .forms import UserForm, EventForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
from datetime import datetime, timedelta, date
from django.utils.safestring import mark_safe
from calendar import HTMLCalendar
from django.views import generic
import calendar
from django.views.generic import View
from django.views.generic import TemplateView, ListView
from django.contrib.auth.models import User
from .utils import Calendar
from .models import Event


# Class based view for base
class base(TemplateView):
    template_name = 'base.html'

# Function based view for registration form
def register(request):
    user_form = UserForm(request.POST or None)

    if request.method == 'POST':
         if user_form.is_valid(): # Check the form validity

             user = user_form.save() # Saving the data to database
             user.set_password(user.password)  # set_password method used to save the password in hashed form
             user.save()  # Saved the hashed password and user
             return HttpResponseRedirect(reverse('app:login'))

         else:
             print(user_form.errors)
    return render(request, 'register.html', {'user_form': user_form})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password) # checks for authentication of the user automatically

        if user:
                login(request,user) # django inbuilt function for login
                return HttpResponseRedirect(reverse('app:calendar'))
        else:
            return render(request, "login.html", {'message': "Username and Password are incorrect"})
    else:
        return render(request,'login.html',{})

@login_required # decorators used if person is logged in
def user_logout(request):
    logout(request) # django inbuilt function for logout
    return HttpResponseRedirect(reverse('app:base'))

class about (TemplateView):
    template_name = 'about.html'

def create_event(request):
    form = EventForm(request.POST or None)
    if request.POST and form.is_valid():
        title = form.cleaned_data['title']
        description = form.cleaned_data['description']
        start_time = form.cleaned_data['start_time']
        end_time = form.cleaned_data['end_time']
        Event.objects.get_or_create(
            user=request.user,
            title=title,
            description=description,
            start_time=start_time,
            end_time=end_time
        )
        return HttpResponseRedirect(reverse('app:calendar'))
    return render(request, 'event.html', {'form': form})

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1) # Gives first day of month
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def CalanderView(request):
    d = get_date(request.GET.get('month', None))
    cal = Calendar(d.year, d.month)
    html_cal = cal.formatmonth(withyear=True)
    event_list = Event.objects.order_by('start_time')
    today = date.today()
    month = d.month
    user=request.user
    return render(request, 'home.html', {'calendar': mark_safe(html_cal), # make_safe in django is used to make html calendar
                                          'prev_month': prev_month(d),
                                          'next_month': next_month(d),
                                          'month':month,
                                          'today':today,
                                          'event':event_list,
                                           'user':user})

def event_details(request, event_id):
    event = Event.objects.get(id=event_id)
    context = {
        'event': event,
    }
    return render(request, 'event_detail.html', context)

class event_details(TemplateView, ListView):

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  About Us
{% endblock %}

{% block head %}

{% endblock %}

{% block content %}
<h1> {{ user.username }} </h1>
<div class="row row-cols-1 row-cols-md-3 g-4" style="margin: 50px 125px; padding: 0px 15px;">
  <div class="col">
    <div class="card">
      <img src="{% static 'images/admin.png' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <center>
          <h5 class="card-title">Kunal Mahajan</h5>
          <p class="card-text">DSAI - 201020427</p>
        </center>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="{% static 'images/admin.png' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <center>
          <h5 class="card-title">Yash Ghodekar</h5>
          <p class="card-text">CSE - 201000059</p>
        </center>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="{% static 'images/admin.png' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <center>
          <h5 class="card-title">Swarup Yeole</h5>
          <p class="card-text">CSE - 201000054</p>
        </center>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">


  <title>
    {% block title %}
      Django Calendar
    {% endblock %}
  </title>


  {% block head %}
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  {% endblock %}
</head>



<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-3">
   <div class="container-fluid">
     <a class="navbar-brand" href="{% url 'app:base' %}" style="font-size: 1.55rem;">Calendar</a>
     <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
       <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app:calendar' %}">Home</a>
        </li>
        {% endif %}
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app:register' %}">Signup</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app:about' %}">About Us</a>
        </li>

      </ul>
      {% if user.is_authenticated %}
       <span class="navbar-text">
          Welcome {{ user.get_username }}
      {% endif %}
      </span>
      </div>
      </div>
      </nav>
      {% block content %}
        <div id="welcometext">
          <h1>Welcome to</h1>
          <h2>Django-Calendar</h2>
        </div>
      {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script src="{% static 'js/script.js' %}" type="text/javascript"></script>
</body>
</html>

templates/event.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% if user.is_authenticated %}
<div class="#" style="
		margin-top: 5px;
		margin-left: 5px;
">
	<a class="btn btn-outline-dark" href="{% url 'app:calendar' %}"> Calendar </a>
</div>
<form method="post" class="event-form">
	{% csrf_token %}
	<table class="form form-table">
		{{ form|crispy }}
	</table><br>
	<tr><td colspan="2"><button type="submit" class="btn btn-outline-dark"> Submit </button></td></tr>
</form>
</center>
{% else %}
<div>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
	<symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
		<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
	</symbol>
	<symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
		<path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
	</symbol>
	<symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
		<path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
	</symbol>
</svg>
<center class="warning">
<div class="alert alert-danger d-flex align-items-center col-3" role="alert">
<svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
<div>
	You have not logged in !
</div>
</div>
</div>
{% endif %}
{% endblock %}

templates/event_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="btn btn-outline-dark" href="{% url 'app:calendar' %}"> Calendar </a>
<div class="clearfix">
        <h1 class="display-4">Event Name: {{ event.title }}</h1><br>
        <p>From <span style="color: gray;">{{ event.start_time }}</span></p>
        <p> To <span style="color: gray;">{{ event.end_time }}</span></p>
        <hr>
        <p>{{ event.description }}</p>
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  Home Page
{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% static 'CSS/style.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
{{user}}
<div class="clearfix">
  <a class="btn btn-outline-dark left" href="{% url 'app:calendar' %}?{{ prev_month }}"> Previous Month </a>
  <form method="GET" class='year-month'>
   <input class="form-control" type="text" placeholder="Year-Month" name="month">
   <input type='submit' value="GO" class="btn btn-outline-dark right">
 </form>
  <a class="btn btn-outline-dark right new_event" href="{% url 'app:event' %}"> New Event </a>
  <a class="btn btn-outline-dark right next_month" href="{% url 'app:calendar' %}?{{ next_month }}"> Next Month </a>
 </div>
 <div class="calendar-event">
   <div class="event-viewbox">
     <table class="table table-hover">
    <thead>
      <tr>
        <h4 class="display-6">Upcoming Events</h4>
      </tr>
      <hr style="margin: 0;border-top: 1px solid black;opacity: 1;">
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Time</th>
        <th scope="col">Title</th>
      </tr>
    </thead>
    <tbody>
      {% for i in event %}
        {% if month == i.start_time.month %}
        {% if i.start_time.date >= today %}
        {% if i.user.username == user.get_username %}
      <tr>
        <td>{{ i.start_time.date }}</td>
        <td>{{ i.start_time.time }}</td>
        <td>{{ i.title }}</td>
      </tr>
       {% endif %}
       {% endif %}
       {% endif %}
      {% endfor %}
    </tbody>
  </table>
   </div>
  {{ calendar }}
 </div>
{% else %}
<div>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>
<center class="warning">
<div class="alert alert-danger d-flex align-items-center col-3" role="alert">
<svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
<div>
  You have not logged in !
</div>
</div>
</center>
</div>
{% endif %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Login
{% endblock %}

{% block head %}
  
{% endblock %}

{% block content %}

<section id="cover" class="min-vh-100">
<div id="cover-caption">
 <div class="container">
  <div class="row text-white">
    <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
      <h1 class="display-4 py-2 text-truncate" style="color: black">Log In</h1>
        <div class="px-2">
          <form action="{% url 'app:login' %}" class="justify-content-center", method="post">
            {% csrf_token %}
          <div class="form-group">
            <label class="sr-only" for='username'> Username: </label>
            <input type="text" name="username" class="form-control" placeholder="Enter Username">
          </div>
          <div class="form-group">
            <label class="sr-only" for='password'>Password: </label>
            <input type="password" name="password" class="form-control" placeholder="Password">
          </div>
          <br>
          <div style="color: rgb(185, 127, 0);font-size: small;">
            {{ message }} <br>
          </div>
          <br>
          <input class="btn btn-outline-dark" type="submit" value="Login">
        </form>
      </div>
    </div>
  </div>
 </div>
  </div>
</section>

{% endblock %}

templates/register.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  Signup
{% endblock %}

{% block head %}
  
{% endblock %}

{% load crispy_forms_tags %}

<!DOCTYPE html>

  {% block content %}
  <br>
  <center>
    <h1 class="display-4"> Registration Form </h1>
  </center>
   <br>

  <form method="post" style="margin: 0px 500px 0px 500px; ">
      {% csrf_token %}
      {{ user_form|crispy }} <br>
      <center>
        <input type="submit" class="btn btn-outline-dark" value="Submit">
      </center>
  </form>

  {% endblock %}